CREATE DATABASE IF NOT EXISTS `Yu`;
USE `Yu`;

CREATE TABLE IF NOT EXISTS `HEY`(
  `Yooooo` varchar(255) NOT NULL DEFAULT '' COMMENT '!!!!!!!'
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COMMENT='HEY';